version: "3.5"

services:
  db:
    restart: always
    # On-prem, it can be helpul to expose the database and use various analytics products
    # At Samsung we use Metabase to show a detailed dashboard of the storage used.
    # ports:
    # - 5432:5432
  pgadmin:
    restart: always
  backend:
    restart: always
    environment:
    - UWSGI_PROCESSES=8
    # leave an unbound port open, useful for debugging 
    ports:
    - ${QABOARD_PORT_DEBUG:-5152}:3001
    
  proxy:
    restart: always
  cantaloupe:
    restart: always
  