version: "3.5"

services:
  db:
    restart: always
    # volumes:
    # - /WHERE/TO/SAVE/BACKUPS:/backups
    # On-prem, it can be helpul to expose the database and use various analytics products
    # At Samsung we use Metabase to show a detailed dashboard of the storage used.
    # ports:
    # - 5432:5432
  pgadmin:
    restart: always
  backend:
    restart: always
    environment:
    # To use values beyond 128, read
    # * https://stackoverflow.com/a/36452474/5993501
    # * https://uwsgi-docs.readthedocs.io/en/latest/articles/TheArtOfGracefulReloading.html#the-listen-queue
    # * https://stackoverflow.com/questions/43243483/docker-container-increase-listen-queue-size-beyond-128
    # * https://serverfault.com/questions/271380/how-can-i-increase-the-value-of-somaxconn
    - UWSGI_LISTEN_QUEUE_SIZE=1024
    - UWSGI_CHEAPER_ALGO_BUSYNESS=true
    - UWSGI_CHEAPER_INITIAL=16  # initial number of processes
    - UWSGI_PROCESSES=64        # max
    - UWSGI_CHEAPER=8           # minimum
    - UWSGI_STATS=true
    # leave an unbound port open, useful for debugging 
    ports:
    - ${QABOARD_PORT_DEBUG:-5152}:3001
    # https://github.com/compose-spec/compose-spec/blob/master/spec.md#sysctls
    sysctls:
    - net.core.somaxconn=1024

  proxy:
    restart: always
  cantaloupe:
    restart: always
  
  # # Adapted from https://devopsheaven.com/cron/docker/alpine/linux/2017/10/30/run-cron-docker-alpine.html
  # # To trigger a backup manually call: docker-compose -f docker-compose.yml -f production.yml up -d cron-backup-db
  # # docker-compose run /etc/periodic/daily/backup
  # cron-backup-db:
  #   image: postgres:12-alpine
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     # https://www.postgresql.org/docs/9.3/libpq-envars.html
  #     PGHOST: db
  #     PGDATABASE: qaboard
  #     PGUSER: qaboard
  #     PGPASSWORD: password
  #     # when using NFS you often don't want to run as root
  #     AS_USER_NAME: username
  #     AS_USER_GROUP: groupname
  #     AS_USER_UID: user_uid
  #     AS_USER_GID: group_gid
  #   # https://busybox.net/downloads/BusyBox.html
  #   # -f: foreground
  #   # -d: log to stderr, 0 is the most verbose, default 8
  #   command: crond -f -d 0
  #   volumes:
  #   - ./services/db/backup:/etc/periodic/daily/backup:ro
  #   - /WHERE/TO/SAVE/BACKUPS:/backups
