# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Web Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: node-${{ hashFiles('webapp/npm-shrinkwrap.json') }}
        restore-keys: ${{ runner.os }}-node-
    - run: cd webapp && npm ci
    - run: cd webapp && npm run build --if-present
    - run: cd webapp && npm test
